apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: eventconductor
  namespace: observability
  labels: { release: kps }
spec:
  namespaceSelector: { matchNames: [eventconductor] }
  selector:
    matchExpressions:
      - { key: app.kubernetes.io/component, operator: In, values: [orchestrator, forms, rules] }
  endpoints:
    - { targetPort: 8080, path: /actuator/prometheus, interval: 30s }
