  server:
    port: 8191
  app:
    security:
      jwt:
        keystore-path: classpath:keystore.p12
        keystore-password: riuitar
        key-alias: gatekeeper
        key-password: riuitar
  grpc:
    client:
      auth-service: # Este nombre debe coincidir con el de @GrpcClient
        address: 'static://localhost:9191' # O el nombre del servicio en Kubernetes/Consul
        negotiation-type: plaintext # Usa TLS en produccion, pero plaintext para pruebas locales
  spring:
    application:
      name: api-gw
    cloud:
      gateway:
        routes:
#          - id: mi_servicio
#            uri: lb://microservicio-backend
#            predicates:
#              - Path=/api/**
#            filters:
#              - TokenEnrichmentFilter
          - id: static_route
            uri: http://localhost:8107
            predicates:
              - Path=/static/**
          - id: forms_route
            uri: http://localhost:8106
            predicates:
              - Path=/_forms/**
            filters:
              - TokenEnrichmentFilter
          - id: forms_route
            uri: http://localhost:8106
            predicates:
              - Path=/_forms/**
            filters:
              - TokenEnrichmentFilter
          - id: orchestrator_route
            uri: http://localhost:8105
            predicates:
              - Path=/_workflow/**
            filters:
              - TokenEnrichmentFilter
          - id: content_service_route
            uri: http://localhost:8104
            predicates:
              - Path=/_content-service/**
            filters:
              - TokenEnrichmentFilter

          - id: control_plane_route
            uri: http://localhost:8103
            predicates:
              - Path=/_control-plane/**
            filters:
              - TokenEnrichmentFilter

          - id: control_plane_data_route
            uri: http://localhost:8103
            predicates:
              - Path=/_cp-data/**
            filters:
              - TokenEnrichmentFilter

          - id: users_route
            uri: http://localhost:8102
            predicates:
              - Path=/_users/**
            filters:
              - TokenEnrichmentFilter

          - id: booking_route
            uri: http://localhost:8108
            predicates:
              - Path=/_booking/**
            filters:
              - TokenEnrichmentFilter

          - id: shell_route
            uri: http://localhost:8101
            predicates:
              - Path=/**
            filters:
              - TokenEnrichmentFilter

