@REM ---------------------------------------------------------------------------
@REM Minimal Maven wrapper for Windows. Uses a local Maven if present, otherwise
@REM downloads the distribution named in .mvn\wrapper\maven-wrapper.properties.
@REM Generated by EventConductor — replace with the full `mvn wrapper:wrapper`
@REM output if you want the upstream script.
@REM ---------------------------------------------------------------------------
@echo off
setlocal

where mvn >NUL 2>NUL
if %ERRORLEVEL%==0 (
  mvn %*
  exit /b %ERRORLEVEL%
)

echo No Maven found on PATH. Install Maven or run "mvn wrapper:wrapper" to add the full wrapper. 1>&2
exit /b 1
