package io.mateu.workflow.codegen;

import com.fasterxml.jackson.databind.JsonNode;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Turns parsed {@code .ectask} contracts into the Java a worker developer implements against: per
 * contract version an {@code Input}/{@code Output} record, a {@code <Id>V<n>Task} interface that
 * specialises the worker-api {@link io.mateu.workflow.worker.api.TaskHandler} (with a nested
 * {@code TaskFailure} subclass per declared error), and — per group — an {@code @AutoConfiguration}
 * that binds each implemented handler into a {@code TaskRegistration} bean the runtime collects.
 *
 * <p>The version is part of every type name, so a contract's versions coexist unchanged (contracts
 * are append-only). Types use fully-qualified names for everything outside their own package, so no
 * import bookkeeping is needed and the output is stable. The generator is a pure function of the
 * contracts and the base package — no Maven, no filesystem — so it is unit-tested directly.
 */
public final class TaskSourceGenerator {

    private static final String HANDLER = "io.mateu.workflow.worker.api.TaskHandler";
    private static final String FAILURE = "io.mateu.workflow.worker.api.TaskFailure";
    private static final String REGISTRATION = "io.mateu.workflow.worker.api.TaskRegistration";
    private static final String VOID = "java.lang.Void";
    private static final String HEADER =
            "// Generated by the EventConductor workflow-maven-plugin from a task contract. Do not edit.";

    private final String basePackage;

    public TaskSourceGenerator(String basePackage) {
        this.basePackage = basePackage;
    }

    public GeneratedTasks generate(List<JsonNode> contracts) {
        var byGroup = new LinkedHashMap<String, List<JsonNode>>();
        for (var contract : contracts) {
            byGroup.computeIfAbsent(contract.get("group").asText(), g -> new ArrayList<>()).add(contract);
        }

        var files = new ArrayList<GeneratedJavaFile>();
        var configFqns = new ArrayList<String>();
        byGroup.forEach((group, groupContracts) -> {
            var pkg = basePackage + "." + Names.groupPackage(group);
            for (var contract : groupContracts) {
                files.addAll(typesFor(contract, pkg));
            }
            var config = groupConfiguration(group, pkg, groupContracts);
            files.add(config);
            configFqns.add(pkg + "." + config.typeName());
        });

        var imports = configFqns.isEmpty() ? "" : String.join("\n", configFqns) + "\n";
        return new GeneratedTasks(files, imports);
    }

    /**
     * The {@code @SpringBootApplication} class a standalone task service runs. Generated into
     * {@code generated-sources} (never edited), in the base package so the generated
     * configurations and the developer's handler beans are both picked up. Only the standalone
     * variant needs it; a task module added to an existing service does not.
     */
    public GeneratedJavaFile applicationClass(String className) {
        var lastDot = className.lastIndexOf('.');
        var pkg = lastDot < 0 ? basePackage : className.substring(0, lastDot);
        var simple = lastDot < 0 ? className : className.substring(lastDot + 1);
        var body = HEADER + "\npackage " + pkg + ";\n\n"
                + "/** Entry point of the generated standalone task service. Generated — do not edit. */\n"
                + "@org.springframework.boot.autoconfigure.SpringBootApplication\n"
                + "public class " + simple + " {\n"
                + "    public static void main(String[] args) {\n"
                + "        org.springframework.boot.SpringApplication.run(" + simple + ".class, args);\n"
                + "    }\n"
                + "}\n";
        return new GeneratedJavaFile(pkg, simple, body);
    }

    private List<GeneratedJavaFile> typesFor(JsonNode contract, String pkg) {
        var id = contract.get("id").asText();
        var version = contract.get("version").asInt();
        var base = Names.pascal(id) + "V" + version;
        var ref = id + "@" + version;

        var files = new ArrayList<GeneratedJavaFile>();
        var hasInput = hasAttributes(contract.get("input"));
        var hasOutput = hasAttributes(contract.get("output"));

        if (hasInput) {
            files.add(record(pkg, base + "Input", contract.get("input"),
                    "Input of task " + ref + "."));
        }
        if (hasOutput) {
            files.add(record(pkg, base + "Output", contract.get("output"),
                    "Output of task " + ref + "."));
        }
        files.add(handlerInterface(pkg, base, contract, hasInput, hasOutput));
        return files;
    }

    /** Whether a side (input/output) has any attributes; if not, the handler binds it to {@code Void}. */
    private boolean hasAttributes(JsonNode attributes) {
        return attributes != null && attributes.isObject() && attributes.size() > 0;
    }

    private GeneratedJavaFile record(String pkg, String name, JsonNode attributes, String summary) {
        var components = new ArrayList<String>();
        attributes.fields().forEachRemaining(entry -> {
            var attrName = entry.getKey();
            var field = Names.fieldIdentifier(attrName);
            var annotation = field.equals(attrName) ? ""
                    : "@com.fasterxml.jackson.annotation.JsonProperty(\"" + escape(attrName) + "\") ";
            components.add("        " + annotation + javaType(entry.getValue()) + " " + field);
        });
        var body = HEADER + "\npackage " + pkg + ";\n\n"
                + "/** " + summary + " Generated — do not edit. */\n"
                + "public record " + name + "(\n"
                + String.join(",\n", components) + "\n"
                + ") {\n}\n";
        return new GeneratedJavaFile(pkg, name, body);
    }

    private GeneratedJavaFile handlerInterface(String pkg, String base, JsonNode contract,
                                               boolean hasInput, boolean hasOutput) {
        var inputType = hasInput ? base + "Input" : VOID;
        var outputType = hasOutput ? base + "Output" : VOID;
        var ref = contract.get("id").asText() + "@" + contract.get("version").asInt();
        var description = contract.hasNonNull("description") ? " " + contract.get("description").asText() : "";

        var errors = new StringBuilder();
        var errorsNode = contract.get("errors");
        if (errorsNode != null && errorsNode.isArray()) {
            for (var error : errorsNode) {
                errors.append(errorClass(error));
            }
        }

        var body = HEADER + "\npackage " + pkg + ";\n\n"
                + "/** Handler for task " + ref + "." + description
                + " Implement this as a Spring bean. Generated — do not edit. */\n"
                + "public interface " + base + "Task extends " + HANDLER + "<" + inputType + ", " + outputType + "> {\n"
                + errors
                + "}\n";
        return new GeneratedJavaFile(pkg, base + "Task", body);
    }

    private String errorClass(JsonNode error) {
        var code = error.get("code").asText();
        var name = Names.pascal(code);
        var description = error.hasNonNull("description") ? " " + error.get("description").asText() : "";
        var literal = "\"" + escape(code) + "\"";
        return "\n    /** Business error " + code + "." + description + " */\n"
                + "    final class " + name + " extends " + FAILURE + " {\n"
                + "        public " + name + "() { super(" + literal + "); }\n"
                + "        public " + name + "(String reason) { super(" + literal + ", reason); }\n"
                + "    }\n";
    }

    private GeneratedJavaFile groupConfiguration(String group, String pkg, List<JsonNode> contracts) {
        var name = Names.pascal(group) + "TasksAutoConfiguration";
        var beans = new StringBuilder();
        for (var contract : contracts) {
            beans.append(registrationBean(contract));
        }
        var body = HEADER + "\npackage " + pkg + ";\n\n"
                + "/** Registers the implemented tasks of group '" + escape(group)
                + "'. Generated — do not edit. */\n"
                + "@org.springframework.boot.autoconfigure.AutoConfiguration\n"
                + "public class " + name + " {\n"
                + beans
                + "}\n";
        return new GeneratedJavaFile(pkg, name, body);
    }

    private String registrationBean(JsonNode contract) {
        var id = contract.get("id").asText();
        var version = contract.get("version").asInt();
        var base = Names.pascal(id) + "V" + version;
        var inputType = hasAttributes(contract.get("input")) ? base + "Input" : VOID;
        var outputType = hasAttributes(contract.get("output")) ? base + "Output" : VOID;
        var topic = contract.hasNonNull("topic") ? "\"" + escape(contract.get("topic").asText()) + "\"" : "null";
        var method = Names.camel(id) + "V" + version + "Registration";

        return "\n    @org.springframework.context.annotation.Bean\n"
                + "    @org.springframework.boot.autoconfigure.condition.ConditionalOnProperty(\n"
                + "            name = \"eventconductor.tasks." + escape(id) + ".enabled\", matchIfMissing = true)\n"
                + "    public " + REGISTRATION + "<" + inputType + ", " + outputType + "> " + method + "(\n"
                + "            " + base + "Task handler) {\n"
                + "        return new " + REGISTRATION + "<>(\n"
                + "                \"" + escape(id) + "\", " + version + ", " + topic + ", "
                + inputType + ".class, " + outputType + ".class, handler);\n"
                + "    }\n";
    }

    private String javaType(JsonNode attribute) {
        var type = attribute.get("type").asText();
        return switch (type) {
            case "string" -> "java.lang.String";
            case "integer" -> "java.lang.Long";
            case "number" -> "java.math.BigDecimal";
            case "boolean" -> "java.lang.Boolean";
            case "date" -> "java.time.LocalDate";
            case "datetime" -> "java.time.LocalDateTime";
            case "object" -> "com.fasterxml.jackson.databind.JsonNode";
            case "array" -> "java.util.List<" + elementType(attribute.get("items")) + ">";
            default -> "com.fasterxml.jackson.databind.JsonNode";
        };
    }

    private String elementType(JsonNode items) {
        // Every mapped type is already a reference type, so it is a legal generic argument as-is.
        return items == null || !items.has("type") ? "java.lang.Object" : javaType(items);
    }

    private static String escape(String s) {
        return s.replace("\\", "\\\\").replace("\"", "\\\"").replace("\n", "\\n").replace("\r", "\\r");
    }
}
