server:
  port: 8092

spring:
  application:
    name: forms-embedded-git
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:h2:mem:forms;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: false

forms:
  persistence: jpa
  git-import:
    # Optional: set this to the same secret you configure in GitHub repo settings
    # webhook-secret: mysecret
    repositories: []
