server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name grafana.mateu.io;

    ssl_certificate     /etc/letsencrypt/live/grafana.mateu.io/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/grafana.mateu.io/privkey.pem;

    location / {
        proxy_pass http://kps-grafana.observability.svc.cluster.local:80;

        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Real-IP $remote_addr;

        # Grafana Live (WebSocket) + streaming.
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_read_timeout 3600s;
    }
}
