{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "eventconductor.fullname" . }}
  labels:
    {{- include "eventconductor.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: {{ .Values.ingress.orchestratorPath }}
            pathType: Prefix
            backend:
              service:
                name: orchestrator
                port:
                  number: {{ .Values.orchestrator.servicePort }}
          - path: {{ .Values.ingress.formsPath }}
            pathType: Prefix
            backend:
              service:
                name: forms
                port:
                  number: {{ .Values.forms.servicePort }}
          - path: {{ .Values.ingress.rulesPath }}
            pathType: Prefix
            backend:
              service:
                name: rules
                port:
                  number: {{ .Values.rules.servicePort }}
  {{- with .Values.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
