CREATE DATABASE motor;
GRANT ALL PRIVILEGES ON DATABASE motor TO user_app;

CREATE DATABASE camunda;
GRANT ALL PRIVILEGES ON DATABASE camunda TO user_app;

CREATE DATABASE idj;
GRANT ALL PRIVILEGES ON DATABASE idj TO user_app;