spring.application.name=embedded-headless


workflow.mode=embedded
workflow.persistence=memory

,\
  org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration,\
  org.springframework.boot.autoconfigure.data.jpa.JpaRepositoriesAutoConfiguration