spring.application.name=embedded-headless


workflow.mode=embedded
workflow.persistence=memory

spring.autoconfigure.exclude=\
  org.springframework.cloud.stream.config.BindingServiceConfiguration,\
  org.springframework.cloud.stream.config.BindersHealthIndicatorAutoConfiguration,\
  org.springframework.cloud.stream.config.ChannelsEndpointAutoConfiguration,\
  org.springframework.cloud.stream.config.BindingsEndpointAutoConfiguration,\
  org.springframework.cloud.stream.function.FunctionConfiguration,\
  org.springframework.cloud.stream.binder.kafka.streams.KafkaStreamsBinderSupportAutoConfiguration,\
  org.springframework.cloud.stream.binder.kafka.streams.function.KafkaStreamsFunctionAutoConfiguration,\
  org.springframework.cloud.stream.binder.kafka.streams.ExtendedBindingHandlerMappingsProviderAutoConfiguration,\
  org.springframework.cloud.stream.binder.kafka.streams.endpoint.KafkaStreamsTopologyEndpointAutoConfiguration,\
  org.springframework.cloud.stream.binder.kafka.config.ExtendedBindingHandlerMappingsProviderConfiguration,\
  org.springframework.cloud.stream.binder.kafka.config.MessageConverterHelperConfiguration,\
  org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration,\
  org.springframework.boot.autoconfigure.data.jpa.JpaRepositoriesAutoConfiguration